Controllers/TweetController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using My_twitter_333.Models;
using Tweetinvi;
using Tweetinvi.Models;
using Tweetinvi.Parameters;

namespace My_twitter_333.Controllers
{
    public class TweetController : Controller
    {
        private readonly TwitterDbContext _context;
        public TweetController(TwitterDbContext context)
        {
            _context = context;
        }

        // GET: TweetController
        public ActionResult Index()
        {
            return View("Index");
        }

        // GET: TweetController/Details/5
        public ActionResult Details(int id)
        {
            return View("Details");
        }

        // GET: TweetController/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: TweetController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Create");
            }
        }

        // GET: TweetController/Edit/5
        public ActionResult Edit(int id)
        {
            return View("Edit");
        }

        // POST: TweetController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Edit");
            }
        }

        // GET: TweetController/Delete/5
        public ActionResult Delete(int id)
        {
            return View("Delete");
        }

        // POST: TweetController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Delete");
            }
        }

        // GET: TweetController/List
        public ActionResult List()
        {
            return View("List");
        }
    }
}

Controllers/TwitterAccountController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using My_twitter_333.Models;

namespace My_twitter_333.Controllers
{
    public class TwitterAccountController : Controller
    {
        private readonly TwitterDbContext _context;
        public TwitterAccountController(TwitterDbContext context)
        {
            _context = context;
        }

        // GET: TwitterAccountController
        public ActionResult Index()
        {
            return View("Index");
        }

        // GET: TwitterAccountController/Details/5
        public ActionResult Details(int id)
        {
            return View("Details");
        }

        // GET: TwitterAccountController/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: TwitterAccountController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Create");
            }
        }

        // GET: TwitterAccountController/Edit/5
        public ActionResult Edit(int id)
        {
            return View("Edit");
        }

        // POST: TwitterAccountController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Edit");
            }
        }

        // GET: TwitterAccountController/Delete/5
        public ActionResult Delete(int id)
        {
            return View("Delete");
        }

        // POST: TwitterAccountController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Delete");
            }
        }

        //GET TwitterAccountController/List
        public ActionResult List()
        {
            return View("List");
        }
    }
}

Controllers/TwitterConfigurationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using My_twitter_333.Models;

namespace My_twitter_333.Controllers
{
    public class TwitterConfigurationController : Controller
    {
        private readonly TwitterDbContext _context;
        public TwitterConfigurationController(TwitterDbContext context)
        {
            _context = context;
        }

        // GET: TwitterConfigurationController
        public ActionResult Index()
        {
            return View("Index");
        }

        // GET: TwitterConfigurationController/Details/5
        public ActionResult Details(int id)
        {
            return View("Details");
        }

        // GET: TwitterConfigurationController/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: TwitterConfigurationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Create");
            }
        }

        // GET: TwitterConfigurationController/Edit/5
        public ActionResult Edit(int id)
        {
            return View("Edit");
        }

        // POST: TwitterConfigurationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Edit");
            }
        }

        // GET: TwitterConfigurationController/Delete/5
        public ActionResult Delete(int id)
        {
            return View("Delete");
        }

        // POST: TwitterConfigurationController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Delete");
            }
        }

        // GET: TwitterConfigurationController/List
        public ActionResult List()
        {
            return View("List");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My_twitter_333</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Twitter_app</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TwitterAccount" asp-action="Index">Twitter акаунти</a>
                            <ul class="sub-menu">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TwitterAccount" asp-action="Create">Създаване</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TwitterAccount" asp-action="Details">Детайли</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TwitterAccount" asp-action="Edit">Редактиране</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TwitterAccount" asp-action="Delete">Изтриване</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TwitterAccount" asp-action="List">Списък</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TwitterConfiguration" asp-action="Index">Twitter конфигурации</a>
                            <ul class="sub-menu">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TwitterConfiguration" asp-action="Create">Създаване</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TwitterConfiguration" asp-action="Details">Детайли</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TwitterConfiguration" asp-action="Edit">Редактиране</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TwitterConfiguration" asp-action="Delete">Изтриване</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TwitterConfiguration" asp-action="List">Списък</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tweet" asp-action="Index">Туитове</a>
                            <ul class="sub-menu">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tweet" asp-action="Create">Създаване</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tweet" asp-action="Details">Детайли</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tweet" asp-action="Edit">Редактиране</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tweet" asp-action="Delete">Изтриване</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tweet" asp-action="List">Списък</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Twitter_app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Поверителност</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>